import { QRConfig } from '../types';

export const DEFAULT_CONFIG: QRConfig = {
  rawUrl: 'https://www.youtube.com/@seucanal',
  targetUrl: 'https://www.youtube.com/@seucanal',
  channelName: '@seucanal',
  addSubscribeParam: false,

  message: 'INSCREVA-SE NO CANAL',
  customMessage: '',
  subMessage: 'youtube.com/@seucanal',
  showSubMessage: true,
  textSize: 22,
  fontFamily: 'Outfit',
  textWeight: 'bold',

  preset: 'premium',
  layout: 'square',

  qrColor: '#000000',
  bgColor: '#F4F4F5',
  textColor: '#18181B',
  subTextColor: '#71717A',
  accentColor: '#FF0000',
  isTransparentBg: false,
  cardBgColor: '#FFFFFF',
  hasCardContainer: true,

  qrSizeRatio: 65,
  borderRadius: 24,
  borderWidth: 1,
  borderColor: '#E4E4E7',
  padding: 32,
  hasShadow: true,
  shadowIntensity: 40,

  showYoutubeIcon: true,
  iconPosition: 'beside_text',
  iconStyle: 'classic_red',

  errorCorrectionLevel: 'H',
  cornerPreset: 'none',
};

export const STYLE_PRESETS: Record<string, Partial<QRConfig>> = {
  premium: {
    preset: 'premium',
    layout: 'square',
    qrColor: '#09090B',
    bgColor: '#F4F4F5',
    cardBgColor: '#FFFFFF',
    textColor: '#09090B',
    subTextColor: '#71717A',
    borderColor: '#E4E4E7',
    borderWidth: 1,
    borderRadius: 28,
    isTransparentBg: false,
    hasCardContainer: true,
    hasShadow: true,
    shadowIntensity: 45,
    showYoutubeIcon: true,
    iconPosition: 'beside_text',
    iconStyle: 'classic_red',
    message: 'INSCREVA-SE NO CANAL',
    padding: 36,
    qrSizeRatio: 66,
  },
  dark_premium: {
    preset: 'dark_premium',
    layout: 'square',
    qrColor: '#FFFFFF',
    bgColor: '#09090B',
    cardBgColor: '#121215',
    textColor: '#FFFFFF',
    subTextColor: '#A1A1AA',
    borderColor: '#27272A',
    borderWidth: 1,
    borderRadius: 28,
    isTransparentBg: false,
    hasCardContainer: true,
    hasShadow: true,
    shadowIntensity: 60,
    showYoutubeIcon: true,
    iconPosition: 'beside_text',
    iconStyle: 'classic_red',
    message: 'INSCREVA-SE!',
    padding: 36,
    qrSizeRatio: 66,
  },
  youtube: {
    preset: 'youtube',
    layout: 'square',
    qrColor: '#09090B',
    bgColor: '#FAFAFA',
    cardBgColor: '#FFFFFF',
    textColor: '#0F0F0F',
    subTextColor: '#606060',
    borderColor: '#FF0000',
    borderWidth: 2,
    borderRadius: 24,
    isTransparentBg: false,
    hasCardContainer: true,
    hasShadow: true,
    shadowIntensity: 35,
    showYoutubeIcon: true,
    iconPosition: 'beside_text',
    iconStyle: 'classic_red',
    message: 'INSCREVA-SE NO CANAL',
    padding: 36,
    qrSizeRatio: 65,
  },
  transparent: {
    preset: 'transparent',
    layout: 'square',
    qrColor: '#FFFFFF',
    bgColor: '#000000',
    cardBgColor: 'transparent',
    textColor: '#FFFFFF',
    subTextColor: '#D4D4D8',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    isTransparentBg: true,
    hasCardContainer: false,
    hasShadow: false,
    shadowIntensity: 0,
    showYoutubeIcon: true,
    iconPosition: 'beside_text',
    iconStyle: 'classic_red',
    message: 'INSCREVA-SE NO CANAL',
    padding: 24,
    qrSizeRatio: 72,
  },
  minimalist: {
    preset: 'minimalist',
    layout: 'square',
    qrColor: '#000000',
    bgColor: '#FFFFFF',
    cardBgColor: '#FFFFFF',
    textColor: '#000000',
    subTextColor: '#52525B',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    isTransparentBg: false,
    hasCardContainer: false,
    hasShadow: false,
    shadowIntensity: 0,
    showYoutubeIcon: false,
    iconPosition: 'beside_text',
    iconStyle: 'monochrome',
    message: 'INSCREVA-SE',
    showSubMessage: false,
    padding: 24,
    qrSizeRatio: 75,
  },
  capcut_right: {
    preset: 'capcut_custom',
    layout: 'horizontal_right',
    qrColor: '#FFFFFF',
    bgColor: '#000000',
    cardBgColor: 'rgba(18, 18, 22, 0.88)',
    textColor: '#FFFFFF',
    subTextColor: '#A1A1AA',
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1.5,
    borderRadius: 24,
    isTransparentBg: true,
    hasCardContainer: true,
    hasShadow: true,
    shadowIntensity: 50,
    showYoutubeIcon: true,
    iconPosition: 'beside_text',
    iconStyle: 'classic_red',
    message: 'INSCREVA-SE NO CANAL',
    padding: 20,
    cornerPreset: 'bottom_right',
  },
  capcut_left: {
    preset: 'capcut_custom',
    layout: 'horizontal_left',
    qrColor: '#FFFFFF',
    bgColor: '#000000',
    cardBgColor: 'rgba(18, 18, 22, 0.88)',
    textColor: '#FFFFFF',
    subTextColor: '#A1A1AA',
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1.5,
    borderRadius: 24,
    isTransparentBg: true,
    hasCardContainer: true,
    hasShadow: true,
    shadowIntensity: 50,
    showYoutubeIcon: true,
    iconPosition: 'beside_text',
    iconStyle: 'classic_red',
    message: 'INSCREVA-SE NO CANAL',
    padding: 20,
    cornerPreset: 'bottom_left',
  },
};

export const PRESET_MESSAGES = [
  'INSCREVA-SE NO CANAL',
  'INSCREVA-SE!',
  'APONTE A CÂMERA E INSCREVA-SE',
  'ESCANEIE E INSCREVA-SE',
  'SIGA O CANAL',
  'ASSISTA E INSCREVA-SE',
  'VENHA PARA O CANAL',
  'INSCREVA-SE E ACOMPANHE',
];
